[package]
name = "polars-avro"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[features]
pyo3 = [
    "dep:pyo3",
    "dep:pyo3-polars",
    "dep:polars-python",
    "polars-io/python",
    "apache-avro/bzip",
    "apache-avro/snappy",
    "apache-avro/xz",
    "apache-avro/zstandard",
]

[dependencies]
polars = { version = "0.48.1", default-features = false, features = [
    "dtype-array",
    "dtype-categorical",
    "dtype-date",
    "dtype-datetime",
    "dtype-decimal",
    "dtype-i16",
    "dtype-i8",
    "dtype-struct",
    "dtype-time",
    "dtype-u16",
    "dtype-u8",
    "lazy",
    "timezones",
] }
apache-avro = "0.18.0"
polars-arrow = "0.48.1"
polars-io = { version = "0.48.1", features = ["file_cache"] }
polars-plan = { version = "0.48.1", features = ["cloud"] }
polars-python = { version = "0.48.1", optional = true }
polars-utils = "0.48.1"
pyo3 = { version = "0.24.2", optional = true }
pyo3-polars = { version = "0.21.0", features = [
    "lazy",
    "dtype-categorical",
    "dtype-struct",
    "dtype-array",
], optional = true }

[dev-dependencies]
chrono = "0.4.40"
polars = { version = "0.48.1", default-features = false, features = ["fmt"] }
polars-io = { version = "0.48.1", features = ["file_cache", "avro"] }
