# pyarrow withheld its bundled stubs in 25.0.0 because they were incomplete
# (apache/arrow#50168). Delete this file once the wheels ship them again.

class Schema:
    def empty_table(self) -> Table: ...

# only referenced through polars' from_arrow overloads, never constructed here
class Array: ...
class ChunkedArray: ...

class RecordBatch:
    @property
    def schema(self) -> Schema: ...

class Table:
    @property
    def schema(self) -> Schema: ...
    def to_batches(self) -> list[RecordBatch]: ...
